sonar.projectKey=R1A2H1L1_Notas
sonar.organization=r1a2h1l1
sonar.projectName=Notas
sonar.projectVersion=1.0

sonar.sources=src/main/java
sonar.tests=src/test/java
sonar.java.source=17

sonar.host.url=https://sonarcloud.io
